Repository NoaniBarbieri/compasso_project02, pull requests merged in 2022-03, with the labels that each got.

#13 Adjustment central content home page
  src/components/CentralContentHome/styles.js
  src/components/partials/Images/styles.js
  src/components/partials/Texts/styles.js
Labels: bug, documentation

#14 Adjustment footer home page
  public/index.html
  src/components/Footer/footer.js
  src/components/Footer/footer.style.js
  src/components/TimerLogout/style.js
  src/components/partials/Buttons/style.js
Labels: bug, enhancement

#17 Responsive clock
  src/App.js
  src/components/CentralContentHome/styles.js
  src/components/Clock&Date/ClockDate.js
  src/components/Clock&Date/ClockDate.style.js
  src/components/Header/Header.style.js
  src/styles.js
Labels: enhancement

#18 Reset timer function
  src/components/Footer/footer.js
  src/components/TimerLogout/index.js
  src/components/TimerLogout/style.js
  src/components/partials/Buttons/style.js
Labels: enhancement

#15 style: made login page layout responsive
  src/Login.js
  src/assets/images/Logo-Compasso-Branco-hor 1.png
  src/components/LogText.js
  src/components/partials/Images/styles.js
  src/styles.js
Labels: enhancement

#20 login validation functionality
  package-lock.json
  package.json
  src/Login.js
  src/components/LogPassInput.js
  src/components/LogUserInput.js
  src/components/LogUserInvalid.js
  src/styles.js
Labels: enhancement

#19 feat: added routes for login, home and notFound pages
  package-lock.json
  src/App.js
  src/components/TimerLogout/index.js
  src/pages/NotFound/notFound.jsx
  src/pages/NotFound/notFound.style.js
  src/routes.jsx
  yarn.lock
Labels: enhancement
